COMBO_ENABLE = yes
SEND_STRING_ENABLE = yes

CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = yes

#CONSOLE_ENABLE = yes
#MOUSEKEY_ENABLE = no
#MIDI_ENABLE = no
#NKRO_ENABLE = no
#APDAPTIVE_NKRO_ENABLE = no
#STENO_ENABLE = no
#EXTRAKEY_ENABLE = no
